### ISSUE TITLE
Equals sign in Base64Url?

### ISSUE THREAD

**Issue by jacobslusser** [Franzmayr/BaseNTypes#1]
I'm using the following to generate a URL-safe Base64 string:
```cs
str = bytes.ToBase64Url().ToString();
```
The result contains an equals sign at the end as found in standard Base64 encoding, however, to be URL-safe equals signs are typically removed.

Am I using the library correctly, or is this a bug?

**Comment by Franzmayr** [comment]
Hi, jacobslusser.
Sorry for the late response, but i'm not notified about your issue.

A Base64Url encoded string in this library includes the padding characters, because the usage of the padding character is not clearly defined. You can include it or not.
If you want a Base64Url encoded string without the padding character you should use the Base64Jws class (i. e. str = bytes.ToBase64Jws().ToString());
This class does the same as the Base64Url class but removes the padding character respectively adds the missing padding character before decoding.

Hope this helps.
